### ISSUE TITLE
Add Scope to groups

### ISSUE THREAD

**Issue by ndobb** [uwrit/leaf#100]
- Expand ConstraintValue fields to 1000 chars
- Update @groups type to 1000 chars in db
- Add scope at initial JWT creation time

**Comment by cspital** [comment]
Add scope to JWT identity claim as well.

https://github.com/uwrit/leaf/blob/9c000635fd3bb24e24788d369190dc89fc5fd3ed/src/server/API/Jwt/JwtProvider.cs#L74

should be

```csharp
    new Claim(ClaimTypes.Name, identity.ScopedIdentity),
```

In practice, this means that `HttpUserContext.UUID` will look like johndoe@institution.edu@urn:leaf:issuer:instance.tld.

**Comment by ndobb** [comment]
That makes a lot of sense. Sounds good to me.
