### ISSUE TITLE
Query for Admin fails if trying to run using a constrained Concept

### ISSUE THREAD

**Issue by ndobb** [uwrit/leaf#13]
**Summary**

Recently we added the admin flag to allow admins to see all Concepts, regardless of whether they meet user or group criteria constraints for Concepts. This works as expected.

However, if an admin tries to then run a query using the Constrained Concept, the Preflight Check fails, and thus the query fails. 

I believe I traced this to ```[app].[fn_FilterConceptsByConstraint]```, which returns the Concept as ```disallowed```, and thus the ```isAuthorized``` flag is set to 0. Please verify.

**Reproduction steps:**

1. Run the below script (ConceptId is 'Procedures' root) 
```sql
  INSERT INTO [LeafDB].[auth].[ConceptConstraint]
  SELECT '1c05433e-f36b-1410-812b-00ffffffffff', 1, 'zztop@leaf.uw.edu'
```

2. Try to run a query with Procedures or any descendants.

**Suggested fix**

Perhaps we should weave the @isAdmin flag into the Preflight checks as well.

**Comment by cspital** [comment]
I believe this is resolved in #16
