### ISSUE TITLE
Client can't save queries in Gateway mode

### ISSUE THREAD

**Issue by ndobb** [uwrit/leaf#175]
## Problem
In gateway mode, the client is not currently able to save a query.

This is because saved queries require a queryId, which is generated on initial query run. However because the gateway node is never queried directly, it does not generate a queryId for the cohort.

The actual error happens here https://github.com/uwrit/leaf/blob/master/src/ui-client/src/services/queryApi.ts#L52.

**Comment by cspital** [comment]
#177 should set up the API to accept gateway api/cohort/count requests from client, the rest of the flow should just work.
