### ISSUE TITLE
Unable to delete concept referenced in search indexes

### ISSUE THREAD

**Issue by sgchoe** [uwrit/leaf#203]
Foreign key references added to the ConceptForwardIndex and ConceptTokenizedIndex tables by the sp_UpdateSearchIndexTables procedure will prevent concepts from being deleted.  The web admin UI will report success and remove the concept entry from the menu but the concept will still exist in the database and re-appear in the UI after logging out and back in.  Manually deleting the references in those two tables allowed the web admin UI to successfully delete the concept.

**Comment by ndobb** [comment]
Got it, thanks @sgchoe . I've confirmed this is a bug. Fixed in 3.2 https://github.com/uwrit/leaf/commit/e548ea4bbe7c77525c1bb36526ca0593b29f2361
