### ISSUE TITLE
Parent-child relationship lost after moving (re-parenting) concept

### ISSUE THREAD

**Issue by sgchoe** [uwrit/leaf#204]
Here are the steps I took that resulted in the issue, which I was able to reproduce:
1) I created a new top-level concept named 'Diagnoses'.  I set the Name and Full Text fields to 'Diagnoses' and 'Had diagnoses', and selected a SQL set (v_observation) from the 'Table, View, or Subquery' drop-down.  I left the 'WHERE Clause' field empty.  I then clicked on Save, after which the UI displayed a 'saved' confirmation dialog.
2) I then dragged an existing concept named 'SNOMED Diagnoses' onto the newly created 'Diagnoses' concept.  The UI displayed a warning asking me to confirm that I wanted to move the concept under 'Diagnoses'.  I clicked 'Yes, move the Concept' after which the UI showed a 'saved' confirmation dialog and the expand/collapse caret appeared next to the 'Diagnoses' concept allowing me to see that the 'SNOMED Diagnoses' concept was now underneath.
3) I then clicked on the 'SNOMED Diagnoses' concept, selected and copied its 'WHERE Clause' value, clicked on the parent 'Diagnoses' concept and pasted the copied text into the 'WHERE Clause' text field.  I clicked on 'Save', the UI confirmed that the concept had been saved and then the 'SNOMED Diagnoses' child concept disappeared from underneath the 'Diagnoses' concept and the 'Diagnoses' concept's 'Has Child Concepts' toggle was set to false.  Clicking on the 'Has Child Concepts' toggle to set it back to true resolved the problem and showed the 'SNOMED Diagnoses' child concept under 'Diagnoses' again.

**Comment by ndobb** [comment]
@sgchoe thanks. I've confirmed this is a bug. This is fixed in 3.2 https://github.com/uwrit/leaf/commit/65d4fec29482ffe46bd293c448a0044a76364a9d
