### ISSUE TITLE
Unable to delete root-level parent concepts after children have been re-parented

### ISSUE THREAD

**Issue by sgchoe** [uwrit/leaf#206]
When child concepts get re-parented, their RootId values remain the same.  If 'emptying' a root-level parent concept, this prevents deletion with the admin UI as it reports that the 'empty' parent concept still has child concepts underneath it that need to be removed.  Manual correction in the database is required, for example I used "update app.concept set rootid = <new root concept id> where rootid = <old root concept id> and id != rootid", after which I was able to delete the concept using the admin UI.  Not sure if this is the best solution so please let me know if this is not recommended and there's a better solution while still on Leaf 3.0 (?).

**Comment by ndobb** [comment]
@sgchoe I'm not able to recreate this issue. Line ~94 at https://github.com/uwrit/leaf/blob/master/src/ui-client/src/actions/admin/concept.ts#L94 (rootId: newRootId) should handle reparenting, and I'm seeing the rootId update as I move concepts around in both the UI and DB. 

Also, after deleting all child concepts under a root I'm able to delete it in the Admin UI.

Can you please add steps to reproduce? Thanks.

**Comment by sgchoe** [comment]
Hi Nic, I was able to reproduce the issue just now, here the steps I followed from a fresh login:
1) I created a new top-level concept in the admin UI named 'Diagnoses and Observations'.  I entered the Name and Full Text fields, copied over the WHERE Clause field from the existing 'Diagnoses' concept, and selected the same SQL set from the drop-down.
2) The existing 'Diagnoses concept had two child concepts', 'HCPCS', and 'SNOMED', which I dragged over to the new 'Diagnoses and Observations' concept, confirming the move after both.
3) I then clicked on 'Diagnoses', which no longer contained any children, and clicked 'Delete Concept', which returned an error from the admin UI that it couldn't be deleted because it contained child concepts.  I tried logging out and back in and tried again and got the same error; I assume because the API server is being checked and returning a non-zero number of child concepts still underneath 'Diagnoses'.

I've attached screenshots from the UI and some SQL queries I ran after re-parenting to confirm.  You can see in the UI screenshot that the 'Diagnoses' concept's caret is expanded but it has no children left.  

Please let me know if there's any additional information details I can provide that might be helpful.  

![leaf_reparent_rootid_unchanged_1](https://user-images.githubusercontent.com/51516907/59886645-70911300-9385-11e9-8383-db024a79fed7.png)

![leaf_reparent_rootid_unchanged_2](https://user-images.githubusercontent.com/51516907/59886657-7c7cd500-9385-11e9-80f9-e19451a5f8fb.png)

**Comment by ndobb** [comment]
@sgchoe this is perfect, thanks. The client and DB both need to find descendent concepts to update the rootId, as well as the rootId in app.ConceptForwardIndex. I'll link the commit and update this issue when complete.

**Comment by ndobb** [comment]
This is fixed in v3.2 https://github.com/uwrit/leaf/commit/e08c638012860960f9d3e4fc692bdcaf43e7fc6c.
