### ISSUE TITLE
Difficult to click on admin fly-out menu items

### ISSUE THREAD

**Issue by sgchoe** [uwrit/leaf#221]
Our instance is v3.2.  Low priority, but since upgrading from 3.0 it seems pretty difficult to click on the admin menu fly-out items.  Can't remember if the main left nav items always had popover tooltips but that may be related, if not the primary issue.  The issue is the same in the latest versions of Chrome, Firefox and MS Edge on Windows 10 v1803.  I've attached an animated gif, please let me know if you need more information or details.

![leaf_admin_menu](https://user-images.githubusercontent.com/51516907/60210075-9b65e600-9821-11e9-9dd2-a7d9b14ba938.gif)

**Comment by ndobb** [comment]
I can reproduce this. Thanks for letting us know, @sgchoe . The 'Admin' tooltip label is in the foreground and preventing mouse clicks on the subpane. We can address this in a patch.

For now, as a workaround I would suggest using the browser in full screen mode, which (unless your monitor is less than ~1400 pixels wide) will expand the sidepanel and not show the tooltip.

**Comment by ndobb** [comment]
This is fixed in v3.2.1 https://github.com/uwrit/leaf/blob/search-fix/src/ui-client/src/components/Sidebar/SidebarTab.tsx#L50.
