### ISSUE TITLE
Error performing activity (switch to admin interface) after period of inactivity

### ISSUE THREAD

**Issue by sgchoe** [uwrit/leaf#227]
Our instance is v3.2.  It seems like the session is timing out in the API server as the response coming back is a 401 (in headers: 'www-authenticate: Bearer error="invalid_token", error_description="The token is expired"').  We've left the SessionTimeoutMinutes and InactivityTimeoutMinutes values in the API project defaulted at 480 and 20 respectively.  I've seen the forced logout modal in the client before since our upgrade so that seems to be working but maybe there's something I did that suppressed it in this instance since it didn't show up?  I don't know exactly how long I was inactive but it was 20+ minutes.  Please let me know if I can provide any additional information or details.

![leaf_error_login_session_timeout](https://user-images.githubusercontent.com/51516907/60372739-47930280-99c3-11e9-8254-55735f7e469f.png)

**Comment by ndobb** [comment]
Hi @sgchoe, this one is my fault. I discovered #225 late yesterday and retroactively added it to [release 3.2.1](https://github.com/uwrit/leaf/releases/tag/v3.2.1) and re-released it in the hope that it was early enough that no one had yet deployed it.

That clearly backfired here - sorry about that. The offending error was fixed here https://github.com/uwrit/leaf/commit/f687f1db5f3bf61955db7862fbf6beea4d307c0b, and I've redeployed on our local instances with no issue so far. If you re-redeploy the current 3.2.1 release this should be fixed.
