### ISSUE TITLE
Azure AD as IdP

### ISSUE THREAD

**Issue by IsmailTapaal** [uwrit/leaf#250]
Is it possible to connect Leaf authentication with Azure AD as IdP?  We don't have ADFS or Shibboleth IdPs, we just use Azure AD.

**Comment by cspital** [comment]
Hi @IsmailTapaal

Azure AD supports a wide variety of federated authentication mechanisms including SAML2. So it should definitely be possible to connect Leaf authentication to Azure AD through a Shibboleth SP configuration, but that is not something we've done yet and so we don't have any advice or documentation on how to proceed there.

UW Research IT has a working Shibboleth SP instance configured against Fred Hutch's Azure AD for the CTMS project, for example. So I know that it's possible.

Hope that helps.

~Cliff

**Comment by ndobb** [comment]
Just for reference, here's MS documentation for configuring Azure AD with Shibboleth https://docs.microsoft.com/en-us/previous-versions/azure/azure-services/jj205463(v=azure.100)#add-azure-ad-as-a-relying-party. Hope this helps.
