### ISSUE TITLE
visualization tab error

### ISSUE THREAD

**Issue by kstephen0909** [uwrit/leaf#313]
I did a query asking for a count of all patients seen at UWNC in the last 12 months. It returned 140K+ patients, but the visualization tab errors, so I could not get subgroup counts.

I also did a query asking for all UWNC patients seen in the last 30 days and got 30K+ patients. the viz tab returned results but only a viz for age breakdowns. I could not see race breakdowns and we were trying to get subgroup counts to show diversity of the population for a grant a colleague is submitting very soon. did the race breakdown viz get removed?

**Comment by ndobb** [comment]
Hi @kstephen0909, sorry we couldn't fix this sooner. The UWNC in last 12 months visualization now returns data in ~3 seconds, and should be far faster than before. 

The Visualization tab now also includes visualizations for ethnicity, language, and religion, as well as a race/ethnicity/gender table based on the demographic table typically seen in NIH grant applications. Please take a look when you have a moment and let me know if this solves the issues.
