### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#325]
Trying to get Leaf running in dev mode, and getting the error below after clicking *I agree* after the initial group of questions.

I am running the 3.6 api directly from Visual Studio, and the ui in Chrome via `npm start` from the build folder.  Did I configure something wrong?

![image](https://user-images.githubusercontent.com/18190568/81953020-ca697f80-95cc-11ea-9e71-a25207e0c7ed.png)

**Comment by ndobb** [comment]
Hi @pj00, thanks for your question. I'm pretty sure this is due to bug #318 - which we're fixing in v3.7 but haven't released yet. You just need a single 'Root' concept - even a temporary dummy one.

```sql
-- Add a dummy SqlSet
INSERT INTO app.ConceptSqlSet (IsEncounterBased, IsEventBased, SqlSetFrom, Created, CreatedBy, Updated, UpdatedBy)
SELECT 0, 0, 'dbo.Test', GETDATE(), 'pj00', GETDATE(), 'pj00'

-- Add a dummy Root concept
INSERT INTO app.Concept (IsRoot, SqlSetId, UiDisplayName, UiDisplayText, AddDateTime)
SELECT 1, 1, 'Test', 'Test', GETDATE()
```

**Comment by pj00** [comment]
That seems to have done the trick, thanks!  Looking forward to playing around with your very cool looking tool!

**Comment by ndobb** [comment]
Awesome! As others may run into this as well I'll keep the issue open until we release 3.7.
