### ISSUE TITLE
Cannot insert the value NULL into column 'RootId', table 'Leaf.app.ConceptForwardIndex'; column does not allow nulls. INSERT fails.

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#326]
I just went through this tutorial and added pretty much the exact same concepts as in the examples:
https://github.com/uwrit/leaf/blob/master/docs/admin/concept/README.md#the-building-blocks-of-leaf-concepts

When I tried running `sp_UpdateSearchIndexTables` per the **Making Concepts Searchable** section, I get this error.

```
Msg 515, Level 16, State 2, Procedure sp_UpdateSearchIndexTables, Line 157 [Batch Start Line 2]
Cannot insert the value NULL into column 'RootId', table 'Leaf.app.ConceptForwardIndex'; column does not allow nulls. INSERT fails.
```

**Comment by ndobb** [comment]
Hey @pj00, right, the `RootId` must be set in order for you to be able to use the search indexes. You can recursively set it for your concepts with something like this:

```sql
; WITH cte AS
(
    SELECT RootId = c.Id
         , RootUiDisplayName = c.UiDisplayName
         , c.IsRoot
         , c.Id
         , c.ParentId
         , c.UiDisplayName
    FROM app.Concept AS c
    WHERE c.IsRoot = 1
 
    UNION ALL
 
    SELECT cte.RootId
         , cte.RootUiDisplayName
         , c2.IsRoot
         , c2.Id
         , c2.ParentId
         , c2.UiDisplayName
    FROM cte
         INNER JOIN app.Concept c2
            ON c2.ParentId = cte.Id
)
 
UPDATE app.Concept
SET RootId = cte.RootId
FROM app.Concept AS C
     INNER JOIN cte
        ON C.Id = cte.Id
```

**Comment by pj00** [comment]
OK, I think I understand what happened.  The INSERT statement you gave me for #325 did not create a root value, but all the concepts I created from the app today do have one.  Had I deleted the manually inserted concept instead of modifying it, this wouldn't have occurred.  Does that sound about right?

**Comment by ndobb** [comment]
Ah, I should have explained better and considered your initial setup. Right, the above UPDATE statement assumes all the Root concepts have `RootId` populated, and in the case of that initial dummy Root concept SQL I gave you, there was no `RootId`. 

So you could either DELETE the dummy Root concept, or:

1. Set `RootId`s for all Root concepts.
`UPDATE app.Concept SET RootId = Id WHERE IsRoot = 1`

2. Run the recursive code above to set `RootId` for descendant concepts. Then all concepts should have a `RootId`.

3. Run `EXEC app.sp_UpdateSearchIndexTables` to index the concepts for search.

Does that make sense?

**Comment by pj00** [comment]
Yes, that is essentially what I did and the sp worked after that.  It did return a -1 result, is that OK?

**Comment by ndobb** [comment]
Yep, that's fine. The procedure doesn't return any specific data when complete. Try to give search a whirl in the UI. Does it work?

**Comment by pj00** [comment]
Hmm...doesn't seem to, but maybe I'm not doing it right.

I have these concepts:

![image](https://user-images.githubusercontent.com/18190568/82080902-07a43f00-96ab-11ea-9114-1b20f6d5e107.png)

But if I enter "Male" it doesn't do anything while I type, and clears everything when I hit Enter:

![image](https://user-images.githubusercontent.com/18190568/82081011-38847400-96ab-11ea-8bd7-ad35e9a67655.png)

**Comment by ndobb** [comment]
Got it. Okay so first assuming the search index tables were populated I would suggest running the concepts hints sp manually to make sure it returns data:

```sql
DECLARE @terms app.SearchTermTable
      , @rootId UNIQUEIDENTIFIER
	  , @user NVARCHAR(100) = 'admin@localhost'
	  , @groups auth.GroupMembership

INSERT INTO @terms (Id, Term)
VALUES (1, 'mal')

EXEC app.sp_GetConceptHintsBySearchTerms @terms, @rootId, @user, @groups
```

If it does, I would then suggest putting a breakpoint in the API in Visual Studio in `/API/Controllers/ConceptController` at https://github.com/uwrit/leaf/blob/master/src/server/API/Controllers/ConceptController.cs#L42.

**Comment by pj00** [comment]
Sorry, got pulled away from this.  Your code snippet above did not return any data.  This is what the content of the three index files looks like.

![image](https://user-images.githubusercontent.com/18190568/82561667-5e8d9680-9b39-11ea-8beb-e391072fe8f1.png)

**Comment by ndobb** [comment]
Ah, there's a [bit of logic in the stored procedure](https://github.com/uwrit/leaf/blob/master/src/db/obj/app.sp_UpdateSearchIndexTables.StoredProcedure.sql#L36) intended to avoid reprocessing concepts that are already indexed for search, but I think the initial missing `RootId` issue threw things off.

Can you truncate the 3 search index tables, rerun the indexing sp, and try again? 

```sql
TRUNCATE TABLE app.ConceptTokenizedIndex
TRUNCATE TABLE app.ConceptForwardIndex
TRUNCATE TABLE app.ConceptInvertedIndex
EXEC app.sp_UpdateSearchIndexTables
```
(If SQL complains about FKs with the `TRUNCATE` statement `DELETE FROM` instead should work)

**Comment by ndobb** [comment]
BTW in 3.7 I've added logic to autofill the RootIds in to avoid this issue; thanks for your patience :)

**Comment by pj00** [comment]
That worked, thanks!
