### ISSUE TITLE
RoleMapping and roles

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#327]
I'm trying to understand RolesMapping and what the different roles mean in the context of Leaf.  Is there documentation on this?

```json
      "RolesMapping": {
        "User": "urn:mace:users",
        "Super": "urn:mace:supers",
        "Identified": "urn:mace:phi",
        "Admin": "urn:mace:sudos",
        "Federated": "urn:mace:federated"
      }
```

**Comment by ndobb** [comment]
Hey @pj00 we're working on updating and revising our docs and structure. 

In the meantime, @mh2727 could you please give @pj00 an idea of how `RolesMapping` works and what each role does?

**Comment by mh2727** [comment]
Hi @pj00.

Here is a brief summary of the roles in Leaf:

- **User**: This is a regular user with the ability to query that specific Leaf instance; limited to **only de-identified** data by default (users are encouraged to put their IRB info in, even if they only need de-identified data)
- **Super** : Just a placeholder at the moment, we haven't added functionality for this role yet 
- **Identified** : Ability to see PHI **if** user has IRB approval 
- **Admin** : Permission to configure Leaf settings via the admin panel
- **Federated** : If the Leaf instance is federated with other Leaf instances, allows the user to query outside instances as well. (By default, users are confined to only their home Leaf instance)

Additional notes:
1. The functionality that comes with each role is designed not to overlap. E.g., A user cannot see PHI if they are not in the Identified role. Admin role lets a user configure stuff, that's all.
2. All users must be in the **User** role at a minimum, even admins.

**Comment by pj00** [comment]
Perfect, thanks!

**Comment by ndobb** [comment]
Closing as additional documentation has been added https://leafdocs.rit.uw.edu/installation/installation_steps/6_appsettings/.
