### ISSUE TITLE
Whoops!

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#328]
I get a Whoops! message when attempting to access the Visualize or Patient List tabs.  Did I miss a configuration setting?

![image](https://user-images.githubusercontent.com/18190568/82570762-a0bdd480-9b47-11ea-89e5-dd111668bce4.png)

![image](https://user-images.githubusercontent.com/18190568/82570870-ca76fb80-9b47-11ea-867b-bc998790d348.png)

**Comment by ndobb** [comment]
Hey @pj00 , you need to tell Leaf what query to run to retrieve demographic data for your cohort. We have that documented (manually via SQL) [here](https://github.com/uwrit/leaf/blob/master/docs/admin/dataset/README.md#basic-demographics), but it's easier to do via the UI by going to Admin -> Datasets -> Basic Demographics. Note that you need to return the expected columns by exact case sensitive names and with the expected types.

![image](https://user-images.githubusercontent.com/10424962/82572456-30a85200-9b39-11ea-84f0-5e6ef8d47d83.png)

**Comment by pj00** [comment]
Thanks, I was able to get it working.  One strange thing I noticed is that the Patient List shows everyone's age as 89 even though my query is for people >= 90 years old.

![image](https://user-images.githubusercontent.com/18190568/82683112-07112880-9c16-11ea-873a-37a460b71232.png)

**Comment by ndobb** [comment]
Great! Regarding age > 90, you're in de-identified mode, correct? To comply with HIPAA de-de-identification and Safe Harbor requirements, Leaf defaults patients aged over 90 to 89 in de-identified mode. If you're in identified mode, you'll see the real ages.

**Comment by pj00** [comment]
Makes sense, didn't know about that rule.  Thanks for all the help.
