### ISSUE TITLE
Export more than 500 patients at a time 

### ISSUE THREAD

**Issue by elg8993** [uwrit/leaf#353]
Is it possible to allow for more than 500 patients to be exported at a time? This would be an enormous help.

**Comment by ndobb** [comment]
Hi @elg8993, different sites/institutions using Leaf can configure the export limit to be whatever they'd like, as that is a configuration setting an administrator can change (here, https://github.com/uwrit/leaf/blob/master/src/server/API/appsettings.json#L60).

My guess though is that you are using the UW **instance** of Leaf, which is configured to 500 for compliance and policy reasons specific to our institution. If you'd like to discuss further, please email leafsupport at uw.edu.

**Comment by elg8993** [comment]
Ok, thank you.

Best,
Emma

--
Emma Gause, MA
Research Assistant, Harborview Injury Prevention & Research Center
MS Student, Department of Epidemiology
University of Washington
egause@uw.edu<mailto:egause@uw.edu>
<mailto:egause@uw.edu>

[signature_733068657]
