### ISSUE TITLE
Patient list pop-ups within pop-ups not accessible

### ISSUE THREAD

**Issue by elg8993** [uwrit/leaf#354]
I am using Google Chrome: In the patient list, there is a pop-up that appears when you hover the cursor over the blue text "Why can't I see data for all # patients?" and "What is de-identification?" Within these pop-ups there is more blue text which I assume may be links to other resources/information? (e.g. "de-identified mode" or "500 patients at a time"). However, it is impossible to hover over these within pop-up words because as soon as you move the cursor off the original blue words, the pop-up disappears.

There may not be pop-ups within the pop-ups, in which case maybe change the color so they don't look like pop-ups?

This is NOT an urgent request.

**Comment by ndobb** [comment]
It sounds like you are seeing this screen:
![image](https://user-images.githubusercontent.com/10424962/90160574-cd4c4b80-dd46-11ea-8b71-ee2d407f2b23.png)

The blue text are in fact not links, just meant to highlight key information (as many users gloss over details unless we emphasize it, in our experience). 

So there is no further info or pop-ups you are missing.

**Comment by elg8993** [comment]
Ok, sounds good.

Thanks for the clarification.

Best,
Emma

--
Emma Gause, MA
Research Assistant, Harborview Injury Prevention & Research Center
MS Student, Department of Epidemiology
University of Washington
egause@uw.edu<mailto:egause@uw.edu>
<mailto:egause@uw.edu>

[signature_1130316994]
