### ISSUE TITLE
Non-Shibboleth REDCap export

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#359]
We are not using Shibboleth with Leaf, and our usernames don't have an `@{scope}` on the end.  So, when Leaf creates the REDCap project it is granting access to `myusername@` when we need it to grant access to just `myusername`.  I am assuming this what needs to be changed, but I haven't looked too closely at the code TBH:

https://github.com/uwrit/leaf/blob/4e1dbf1d32ab38d112db1bee294324ca8bbb0b4b/src/ui-client/src/providers/redcapExport/redcapExportWebWorker.ts#L398

Simple enough for us to tweak that file to work around the problem, just thought I'd point it out so you could consider the possibility of adding some flexibility in a future release.

**Comment by ndobb** [comment]
@pj00 that's really good to know. In the [REDCap export appsettings section](https://github.com/uwrit/leaf/blob/master/src/server/API/appsettings.json#L63), perhaps leaving a blankstring/null `Scope` could be inferred as no scope, and Leaf could exclude the `@`.

Alternatively we could make it more explicit and have an `IncludeUserScope` boolean setting instead. Thoughts?

**Comment by pj00** [comment]
I think either approach solves the problem for us.  I don't know if there would ever be a scenario where `myusername@` is actually valid/preferred, but I think you cover your bases more if you go with the `IncludeUserScope` approach.

**Comment by ndobb** [comment]
Agreed. Cool, we'll plan to add this in the next release.
