### ISSUE TITLE
Query against list of MRNs

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#361]
Let's say I have an Excel file with a column of 50 MRNs, and I want to run a query that only returns results where the MRN matches one of those 50 MRNs.  How would I accomplish this in Leaf?

**Comment by ndobb** [comment]
Hi @pj00, this is a common use case - we have an ongoing (undocumented) TODO to add a flat-file/delimited text input Import Feature, such that users can copy/paste MRNs in to create their own concepts. In fact, in the old UW-internal Leaf codebase, this was a widely-used feature.

At the moment though, the only way to do this is to do so via the REDCap Import feature (which I can help you troubleshoot through in #360).

**Comment by pj00** [comment]
Good to know, thanks!
