### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by pj00** [uwrit/leaf#363]
Can you point me to the code that cleans/validates the sql that can be entered via the UI, in order to prevent sql injection?  Just doing some due diligence since I'll probably be asked about this when we demo Leaf.

**Comment by ndobb** [comment]
Sure, it's quite simple:

[`ValidateSql()` is called](https://github.com/uwrit/leaf/blob/master/src/server/Model/Compiler/SqlServer/SqlServerCompiler.cs#L54) after building the SQL statement to be executed, which [checks to ensure that no DDL-associated commands exist in the query](https://github.com/uwrit/leaf/blob/master/src/server/Model/Compiler/Common/Dialect.cs#L76).

**Comment by pj00** [comment]
Exactly what I was looking for, thanks!
