### ISSUE TITLE
Error":"nameID header not found, no scoped identity available"

### ISSUE THREAD

**Issue by nivanov-gw** [uwrit/leaf#384]
The SSO with shibboleth accepts the credentials and redirects back to the leaf instance.  The shibd log shows that the user and roles are being retrieved. But leaf server returns error nameID Header not found.  I attached the leaf server log.    

This instance of leaf is running on Windows server 2019 with iis10.  

This is what shibd is showing:

<Subject><NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">nivanov@gwu.edu</NameID><SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><SubjectConfirmationData InResponseTo="_eec7ec6524609d77c039197f62ec21f0" NotOnOrAfter="2021-01-27T20:34:48.102Z" Recipient="https://sphcbi-leaf.ead.gwu.edu/Shibboleth.sso/SAML2/POST"/></SubjectConfirmation></Subject><Conditions NotBefore="2021-01-27T19:29:48.102Z" NotOnOrAfter="2021-01-27T20:34:48.102Z"><AudienceRestriction><Audience>https://sphcbi-leaf.ead.gwu.edu/shibboleth</Audience><Attribute Name="http://schemas.microsoft.com/claims/authnmethodsreferences"><AttributeValue>http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password</AttributeValue><AttributeValue>http://schemas.microsoft.com/claims/multipleauthn</AttributeValue></Attribute><Attribute Name="emailaddress"><AttributeValue>nivanov@gwu.edu</AttributeValue></Attribute><Attribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6"><AttributeValue>nivanov@gwu.edu</AttributeValue></Attribute><Attribute Name="nameID"><AttributeValue>nivanov@gwu.edu</AttributeValue></Attribute><Attribute Name="role"><AttributeValue>leaf-user;leaf-admin</AttributeValue></Attribute></AttributeStatement><AuthnStatement AuthnInstant="2021-01-27T19:34:36.410Z" SessionIndex="_7dc3813a-6cd6-4bb5-997e-5486be2e0200"><AuthnContext><AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef></AuthnContext></AuthnStatement></Assertion></samlp:Response>

[leaf-api-20210127.log](https://github.com/uwrit/leaf/files/5882660/leaf-api-20210127.log)

**Comment by ndobb** [comment]
Hi @nivanov-gw, what does the browser show if you navigate to `<your_leaf_url>/Shibboleth.sso/Session`? I just want to confirm the expected attributes are present and named accordingly (you may need to set `showAttributeValues` to `true`  for debugging purposes - https://stackoverflow.com/a/31173098).

Also, can you share the [`Authentication`](https://github.com/uwrit/leaf/blob/master/src/server/API/appsettings.json#L25) and [`Authorization`](https://github.com/uwrit/leaf/blob/master/src/server/API/appsettings.json#L36) sections of your `appsettings.json` file?

If you'd prefer to discuss by email as well that's fine. I can update the Leaf docs based on what we find.

**Comment by ndobb** [comment]
Closing as this has been resolved.
