### ISSUE TITLE
LEAF_REDCAP_SUPERTOKEN environment variable is not optional

### ISSUE THREAD

**Issue by marshall-ucsd** [uwrit/leaf#404]
The `LEAF_REDCAP_SUPERTOKEN` environment variable is listed as optional, but our Leaf instance wouldn't start without the variable defined. Defining it with a dummy value was sufficient, so an easy workaround.

Looking at the code, the issue may be in `ConfigureExportOptions()`, which invokes `config.GetByProxy(Config.Export.REDCap.SuperToken)` - `GetByProxy` raises an exception if the environment variable is not set. `GetByProxy` probably needs an _IsRequired_ option to resolve cleanly.

**Comment by ndobb** [comment]
Hi @marshall-ucsd, thanks for taking a look. Looking at the code, however, can you confirm that your [appsettings.json REDCap.Export](https://github.com/uwrit/leaf/blob/master/src/server/API/appsettings.json#L68) value is set to `false`?

The line at https://github.com/uwrit/leaf/blob/master/src/server/API/Options/StartupExtensions.Options.cs#L173 should prevent the SuperToken from being needed if REDCap export is disabled, though if there's indeed a bug we're happy to take a look.

Best,
-nic

**Comment by marshall-ucsd** [comment]
I'm pretty sure we turned off all REDCap settings, but we'll double-check.

**Comment by ndobb** [comment]
@marshall-ucsd any updates on this one, or can I close the ticket?

**Comment by marshall-ucsd** [comment]
Yes, the REDCap setting was definitely set to false, but generated errors until the variable was set with a dummy variable.

**Comment by ndobb** [comment]
We've tried but were unable to produce this error on a local dev machine. We've also confirmed we have at least one running production Leaf instance with no `LEAF_REDCAP_SUPERTOKEN` defined that runs without issue.

If you can send your appsettings file and a screenshot of a your environment variables (sensitive info removed) we're happy to try to dig further, but I'm closing the issue for now.
