### ISSUE TITLE
Allow disabling user logout

### ISSUE THREAD

**Issue by ndobb** [uwrit/leaf#417]
For various reasons (see https://uit.stanford.edu/service/saml/logout) in certain cases it may not be helpful to allow users to logout, specifically in an SSO context where the Leaf-associated session logout may complicate session state associated with other applications.

To handle these cases in Leaf, we would need to:
1. Ensure the server disallows `api/user/logout` 
2. Hide the `Logout` dropdown option in the client

I'd propose the appsettings configuration be used for these cases, specifically modifying it to be

```json
// appsettings.json

...
"Authentication": {
    "Logout": {
       "Enabled": false,
       "URI": ""
    }
  },
```
With `Authentication.Logout.URI` replacing the current `Authentication.LogoutURI`.

@artgoldberg does the above sound reasonable?

**Comment by artgoldberg** [comment]
Yes, that's reasonable @ndobb . Thanks.
