### ISSUE TITLE
Patient Age field empty in Patient List

### ISSUE THREAD

**Issue by artgoldberg** [uwrit/leaf#434]
Hi Leaf folks

Using our Leaf instance (running [Leaf 3.9.1](https://github.com/uwrit/leaf/tree/3.9.1)) I find that the Age field is blank for all patients in Patient List. However, I know that certain patients have complete DOB info in the `person` table, so I expect them to have Age values.

This is the Basic Demographics query:

    SELECT
          personId          = CONVERT(NVARCHAR(10),P.person_id)
        , addressPostalCode = L.zip
        , addressState      = CONVERT(NVARCHAR(20), L.[state])
        , birthDate         = P.birth_datetime
        , deceasedDateTime  = D.death_datetime
        , ethnicity         = c_ethnicity.concept_name
        , gender            = c_gender.concept_name
        , deceasedBoolean   = CONVERT(BIT, CASE WHEN D.person_id IS NULL THEN 1 ELSE 0 END)
        , hispanicBoolean   = CONVERT(BIT, CASE WHEN c_ethnicity.concept_name = 'Hispanic or Latino' THEN 1 ELSE 0 END)
        , marriedBoolean    = CONVERT(BIT, 0)
        , [language]        = CONVERT(NVARCHAR(1),NULL) /* Not in OMOP */
        , maritalStatus     = CONVERT(NVARCHAR(1),NULL) /* Not in OMOP */
        , mrn               = CONVERT(NVARCHAR(1),NULL) /* Not in OMOP */
        , name              = CONVERT(NVARCHAR(1),NULL) /* Not in OMOP */
        , race              = c_race.concept_name
        , religion          = CONVERT(NVARCHAR(1),NULL) /* Not in OMOP */
        FROM [omop].[cdm_std].[person] AS P
            LEFT JOIN omop.cdm_std.concept AS c_gender
                ON P.gender_concept_id = c_gender.concept_id
            LEFT JOIN omop.cdm_std.concept AS c_race
                ON P.race_concept_id = c_race.concept_id
            LEFT JOIN omop.cdm_std.concept AS c_ethnicity
                ON p.ethnicity_concept_id = c_ethnicity.concept_id
            LEFT JOIN omop.cdm_std.[location] AS L
                ON P.location_id = L.location_id
            LEFT JOIN omop.cdm_std.death AS D
                ON P.person_id = D.person_id

The Age field is blank in Patient List.

However, patients in the list - verified for one of them - contain fully initialized DOB attributes.

Thanks
Arthur

**Comment by ndobb** [comment]
Likewise @artgoldberg! Ah that's a great point, thanks for catching that. I'll update the script with that change.
