### ISSUE TITLE
ConceptPatientYearCount.Year needs to be a string

### ISSUE THREAD

**Issue by ndobb** [uwrit/leaf#44]
Clinical DBs have wacky dates, and the way we had handled this in the past (see pic below) was by
* Making ```null``` dates a ```?```
* Grouping dates prior to 1995 as ```<1995```
* Grouping dates farther in the future than the current year as ```>2019```

We can devise a different way of handling this than allowing ```string```s for the Year, but I'm inclined to change this from ```int``` to a ```string``` unless we have other options.

The relevant model is here https://github.com/uwrit/leaf/blob/master/src/server/Model/Compiler/ConceptPatientYearCount.cs#L11. 

Note that changing this will also require we filter out non-numeric Year values prior to computing the estimated query cost and sorting the panels here https://github.com/uwrit/leaf/blob/master/src/server/Model/Compiler/CteCohortQueryContext.cs#L37 before SQL compilation.

![image](https://user-images.githubusercontent.com/10424962/55665606-9895bf00-57f7-11e9-8c09-cb3b78dba6f8.png)

**Comment by cspital** [comment]
slated for v3.2

**Comment by cspital** [comment]
Year is now a nullable integer, client will be responsible for aggregating out of range years for presentation.
