### ISSUE TITLE
Mechanism to take Leaf off-line temporarily for maintenance

### ISSUE THREAD

**Issue by artgoldberg** [uwrit/leaf#453]
It would be handy to automatically take Leaf off-line temporarily for maintenance. 

Please see discussion #446 .

Thanks
Arthur

**Comment by artgoldberg** [comment]
A related question is "What queries should be executed against the LeafDB to determine whether it is being actively used?"

**Comment by ndobb** [comment]
@artgoldberg, I think there may be a few interrelated features to be added here that could help most Leaf sites. Let's discuss at our next chat. I don't think adding them would be too heavy a lift.
