### ISSUE TITLE
Permission Denied Error When Running Leaf API in Debug Mode

### ISSUE THREAD

**Issue by olayemiibrahim** [uwrit/leaf#456]
### Discussed in https://github.com/uwrit/leaf/discussions/455

<div type='discussions-op-text'>

<sup>Originally posted by **olayemiibrahim** September 28, 2021</sup>
I receive the following error when I compile and run the Leaf API in Debug mode.

```
 Loaded: loaded (/var/opt/leafapi/services/leaf_api_unsecure.service; linked; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-09-28 15:47:40 UTC; 12s ago
  Process: 11284 ExecStart=/usr/bin/dotnet API.dll (code=exited, status=1/FAILURE)
 Main PID: 11284 (code=exited, status=1/FAILURE)

Sep 28 15:47:40 appserver systemd[1]: Started Leaf API Service.
Sep 28 15:47:40 appserver dotnet[11284]: System.UnauthorizedAccessException: Access to the path '/home/api_svc_account/.dotnet' is denied.
Sep 28 15:47:40 appserver dotnet[11284]: ---> System.IO.IOException: Permission denied
Sep 28 15:47:40 appserver dotnet[11284]: --- End of inner exception stack trace ---
Sep 28 15:47:40 appserver dotnet[11284]: at System.IO.FileSystem.CreateDirectory(String fullPath)
Sep 28 15:47:40 appserver systemd[1]: leaf_api_unsecure.service: main process exited, code=exited, status=1/FAILURE
Sep 28 15:47:40 appserver systemd[1]: Unit leaf_api_unsecure.service entered failed state.
Sep 28 15:47:40 appserver systemd[1]: leaf_api_unsecure.service failed.
```

I don't receive this error when compiling and running the API as a release.</div>

**Comment by ndobb** [comment]
At a quick glance, this is seems pretty transparent to me - looks like a permissions issue. I'd suggest ensuring the user account running under `systemd` has write access to that directory.

**Comment by olayemiibrahim** [comment]
I'm not seeing that /home/api_svc_account/ exists so I'm curious as to why it's attempting to access that directory.

**Comment by ndobb** [comment]
Can you post your `systemd` `.service` file?

**Comment by olayemiibrahim** [comment]
```
[Unit]
Description=Leaf API Service

[Service]
EnvironmentFile=/var/opt/leafapi/services/leaf_api.service.conf
User=api_svc_account         
Type=idle
TimeoutStartSec=300
TimeoutStopSec=30
WorkingDirectory=/var/opt/leafapi/api_unsecure/
ExecStart=/usr/bin/dotnet API.dll

[Install]
WantedBy=multi-user.target
```

**Comment by ndobb** [comment]
So you are defining a `User`, `api_svc_account` - is this a real user? Does it have permission to run the API.dll file? (also, does it have permission to query your databases, down the road?)

Note that there is no Leaf code running here, just `systemd` and `dotnet`.

**Comment by olayemiibrahim** [comment]
I used the following commands in step 8 in the documentation to create the nologin user `api_svc_account`

```
$ useradd -r api_svc_account
$ chown /var/log/leaf/
$ chown -R /var/opt/leafapi/
```
From these commands it should have permissions to the entire leafapi directory which contains the API.dll file

**Comment by mh2727** [comment]
Hi @olayemiibrahim.

That's not necessarily true. Although changing the owner gives the user control of the directory, it does not mean the permission settings are set up that way. A `user` can be the owner of a directory, but still unable to write to it.

Can you check your permissions for the user `api_svc_account` by running `ls -l` on the `/var/log/` and `/var/opt/` locations and ensuring a `700` on the `leaf` and `leafapi` directories? This will give the user full access to the directories.

**Comment by olayemiibrahim** [comment]
The API was copied to the wrong folder, issue on my end.
