### ISSUE TITLE
At A Glance Horizontal Bucket Charts Cutting Off Left Numbers

### ISSUE THREAD

**Issue by cspital** [uwrit/leaf#46]
**Summary**
On heavily skewed result sets, the left side numbers of the At a Glance bars are getting cut off.

**Reproduction Steps**
Simple query like:
Any patients who `Identify as Black or African American`.

Returns 6171 patients, of which 5898 are living and 273 are deceased.

Run query, go to Visualize. The 5 digit is cut-off. Resize the window does not help.

**Comment by ndobb** [comment]
Got it, thanks.
