### ISSUE TITLE
Timeline (limited to 5000 patients) 

### ISSUE THREAD

**Issue by EddieAtUniversityofColorado** [uwrit/leaf#499]
Hello, I'm encountering a problem when I attempt to use the Timeline feature in Leaf. Here is what I'm seeing. 

1. I run my initial query, get a result with 981,208 patients. 
2. I choose timeline for the left panel and I select my result from step 1 as my index event, panel 1. 
3. I click "+ Add Concepts (0 selected) for the 2nd step of the timeline feature, and I choose a concept with over 900,000 records and I drag that over to the field that reads "Drag and Drop Concepts for All Data." 
4. Leaf is giving me an "error" / message: "Timeline (limited to 5000 patients) of 6 Month Increments Before and After index event."

Any ideas on how I can fix this?

**Comment by ndobb** [comment]
Hi @EddieAtUniversityofColorado - that is an incredibly large cohort and presumably heavy query for the database to pull in a reasonable time.

Please provide more context: do you get the same errors with smaller cohorts (eg, < 1000 patients)?

Also, what do the Leaf log files say? (I'm guessing the query just times out, but it's good to be sure)

**Comment by EddieAtUniversityofColorado** [comment]
Hello Nic, I'm not getting the same errors with smaller cohorts. I'm getting it to function with cohorts of 400+ and 900+.  I can find out what the log-files say.

**Comment by ndobb** [comment]
Those would be the app server log files. They'll almost certainly say that the query just timed out, I suspect.

I don't think there is a one-size-fits-all solution for this kind of thing, as if the SQL query is slow, the tuning of it will be specific to a given site's clinical database.

**Comment by EddieAtUniversityofColorado** [comment]
@ndobb I think you're right. The tuning is where we are for this particular issue and some other other query-performance issues. Thank you!
Eddie
