### ISSUE TITLE
Implicit Conversion error

### ISSUE THREAD

**Issue by nixj14** [uwrit/leaf#539]
Ran into implicit conversion errors issues when building (LeafDbDataReader.cs).  Created a PR with a fix:

https://github.com/uwrit/leaf/pull/538

**Comment by ndobb** [comment]
Thanks @nixj14. Interestingly I think this may be a dotnet version issue (I suspect the C# compiler handles inference better in this case in more recent versions), per [this conversation](https://github.com/uwrit/leaf/discussions/528#discussioncomment-2881192) with our collaborators at Mount Sinai.

In any case I think the explicit conversion is a good idea anyway - thank you very much for making the PR. Merged!
