### ISSUE TITLE
Allow Dynamic Datasets

### ISSUE THREAD

**Issue by ndobb** [uwrit/leaf#95]
FHIR templates can't cover all possible kinds of data, and there are a number of use cases that would benefit from dynamic datasets, in other words datasets whose columns are defined by an admin instead of adhering to a FHIR dataset interface. 

Dynamic dataset configuration will require settings for:

- `IsLongitidunal` - indicator for whether there are potentially more than one row per patient. If `true`, the dataset should require the `EncounterId` be returned.
- `SqlDateField` - if `IsLongitudinal` is `true`, a date field *must* also be defined.
- `SqlStringValueField` - if `IsLongitudinal` is `true`, a string value field *must* also be defined. This field is passed to the client for data aggregation.
- `SqlNumericValueField` - if `IsLongitudinal` is `true`, a numeric value field *may* also be defined. This field is passed to the client for data aggregation.
- `Fields` - a JSON object array matching how FHIR shapes are stored in ref.Shape, with each object listing {"name":"exampleFieldName","type":"String","phi":false,"mask":false,"required":true}. Alternatively, we could also normalize this as it's own DB table. 

---
### DB
- [x] Add `DynamicConfiguration` field to `app.DatasetQuery`. JSON representation of above configuration data.
- [x] Add `DynamicConfiguration` field to second return table of `app.sp_GetDatasetContextById`. It should only be populated if Shape is the Dynamic value.

### API
- [x] Add `DynamicConfiguration` property to `DatasetQueryRecord` and `DatasetQuery`.
- [x] Add JSON SerDe functionality to `DatasetQueryRecord` to enable conversion of configuration to and from database storage formats.
- [x] Add `DynamicConfigurationValidator` to enforce rules above.
- [x] Add any required pre-query validation to `DatasetCompilerValidationContextProvider.GetContextState`.
- [x] Create `DynamicDataset` derivation of `ShapedDataset`, will use a `Dictionary<string, object>` to contain data elements.
- [x] `Services.Cohort.DatasetExecutor` needs to be Dynamic Dataset aware. 
- [x] `Model.Cohort.ShapedDatasetSchema` needs to be able to take a DynamicConfiguration and produce a schema.
- [x] `Model.Anonymization` needs a dynamic dataset anonymizer impl.
- [x] `Services.Cohort.DatasetMarshaller` needs a Dynamic DatasetMarshaller impl.
- [x] `Model.Cohort.Dataset.Results` should be changed to `Dictionary<string, IEnumerable<object>>` instead. Give ShapedDataset an `object Result()` method that returns `this`. Dynamic dataset should override and unroll the dictionary into an ExpandoObject.

**Comment by cspital** [comment]
Prioritize Dataset.Results impl and tests, then DynamicValidationEngine, then DynamicAnonymizer.
